 name: fr_xgb
channels:
  - conda-forge
dependencies:
  - python=3.8.3
  - numpy=1.23.4
  - pandas=1.5.1
  - xgboost=1.6.2
  - scikit-learn=1.1.2
  - scikit-optimize=0.9.0
  - matplotlib=3.6.1
  - csv=1.0
  - logging=0.5.1.2
  - conda-pack